[build]
  command = "vite build"
  publish = "dist"

  [[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
    for = "assets/*.js"
    [headers.values]
        Content-Type = "application/javascript"
        Cache-Control = "no-store"