[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
    for = "dist/assets/*.js"
    [headers.values]
        Content-Type = "application/javascript"